export const faqData = [
  {
    question: "What is a QR code?",
    answer: "A QR (Quick Response) code is a two-dimensional barcode that can be read by smartphones and QR scanners. It can store various types of information, such as web links, text, contact details, or WiFi passwords."
  },
  {
    question: "Are QR codes free to use?",
    answer: "Yes! Our QR code generator is completely free. There are no hidden fees, no signup required, and your QR codes will never expire."
  },
  {
    question: "What's the difference between static and dynamic QR codes?",
    answer: "Static QR codes encode the data directly into the image. Once created, the destination cannot be changed. Dynamic QR codes encode a short URL that redirects to your final destination, allowing you to update the destination anytime and track scans. Our tool generates static QR codes."
  },
  {
    question: "What image format should I download — PNG or SVG?",
    answer: "PNG is a raster image format perfect for everyday use on screens and simple printing. SVG is a vector format that can be scaled infinitely without losing quality, making it ideal for professional printing, large banners, and graphic design."
  },
  {
    question: "Can I add a logo to my QR code?",
    answer: "Yes, you can easily add a logo or an image to the center of your QR code using our customization tools. Just click the 'Upload Logo' button and select your image."
  },
  {
    question: "How do I make a QR code for my WiFi?",
    answer: "Select the 'WiFi' tab in our generator, enter your network name (SSID), password, and security type. Anyone who scans the resulting QR code will automatically connect to your network."
  },
  {
    question: "How long do QR codes last?",
    answer: "The QR codes generated by our tool are static, meaning they last forever and will never expire, as long as the information they point to (like a website URL) remains active."
  },
  {
    question: "What is error correction in QR codes?",
    answer: "Error correction allows a QR code to remain readable even if it is partially damaged, dirty, or covered (for example, by a logo in the center). There are four levels: L (7%), M (15%), Q (25%), and H (30%). Higher levels make the code denser but more resilient."
  },
  {
    question: "Can QR codes be scanned from a screen?",
    answer: "Yes, modern smartphones and tablets can easily scan QR codes displayed on other screens, such as a computer monitor or a TV."
  },
  {
    question: "How many characters can a QR code hold?",
    answer: "A standard QR code can hold up to 4,296 alphanumeric characters, but it's best to keep the data as short as possible to ensure the code remains easy to scan."
  }
];
